services:
  - type: web
    name: techronyx-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn ecomm.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ecomm.settings
      - key: SECRET_KEY
        value: django-insecure-qz=9jrtni-hd(*+j*bu!qq)o=h)8fl4)@k3!@_jifgl$5_wv3*
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        value:postgresql://techronyxuser:vKxqSc19QN1qOIT3DljrX8bvEdGtKPSj@dpg-d21h37h5pdvs73ftoom0-a/techronyxdb
