services:
  - type: web
    name: techronyx-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate --noinput && gunicorn ecomm.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ecomm.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: techronyx-fullstackweb.onrender.com
      - key: DATABASE_URL
        sync: false
